export const MARCH_OFFER_DIALOG_SESSION_KEY = "showMarchOfferModal";
export const MARCH_OFFER_DIALOG_DELAY_MS = 1500;
export const MARCH_OFFER_DIALOG_MAX_WAIT_MS = 6000;
export const MARCH_OFFER_END_DATE_LABEL = "31.03.2026";
