// Sample chess games data array
export const chessGamesData = [
    {
      id: 1,
      date: "2024-03-20",
      opponent: "ChessMaster2000",
      result: "WIN",
      eloChange: "(+12 ELO Rating)",
      resultColor: "text-green-500",
      rating: "1950",
      opening: "Sicilian Defense",
      moves: "45",
      timeControl: "10+0",
      source: "PGN Upload",
      gameType: "Blitz",
      color: "White",
      gameFormat: "PGN Upload"
    },
    {
      id: 2,
      date: "2024-03-18",
      opponent: "GrandMaster42",
      result: "LOSS",
      eloChange: "(-8 ELO Rating)",
      resultColor: "text-red-500",
      rating: "2100",
      opening: "French Defense",
      moves: "32",
      timeControl: "5+3",
      source: "Online Games",
      gameType: "Blitz",
      color: "Black",
      gameFormat: "Online Games"
    },
    {
      id: 3,
      date: "2024-03-15",
      opponent: "KnightRider88",
      result: "DRAW",
      eloChange: "(+0 ELO Rating)",
      resultColor: "text-gray-500",
      rating: "1875",
      opening: "Queen's Gambit",
      moves: "60",
      timeControl: "15+10",
      source: "Tournaments",
      gameType: "Rapid",
      color: "White",
      gameFormat: "Tournaments"
    },
    {
      id: 4,
      date: "2024-03-10",
      opponent: "BishopBrawler",
      result: "WIN",
      eloChange: "(+15 ELO Rating)",
      resultColor: "text-green-500",
      rating: "1825",
      opening: "Ruy Lopez",
      moves: "38",
      timeControl: "3+2",
      source: "Online Games",
      gameType: "Bullet",
      color: "Black",
      gameFormat: "Online Games"
    },
    {
      id: 5,
      date: "2024-03-05",
      opponent: "PawnPusher123",
      result: "WIN",
      eloChange: "(+7 ELO Rating)",
      resultColor: "text-green-500",
      rating: "1780",
      opening: "King's Indian Defense",
      moves: "52",
      timeControl: "30+0",
      source: "PGN Upload",
      gameType: "Classical",
      color: "White",
      gameFormat: "PGN Upload"
    },
    {
      id: 6,
      date: "2024-02-28",
      opponent: "RookRampager",
      result: "LOSS",
      eloChange: "(-10 ELO Rating)",
      resultColor: "text-red-500",
      rating: "2050",
      opening: "Caro-Kann Defense",
      moves: "29",
      timeControl: "10+5",
      source: "Tournaments",
      gameType: "Rapid",
      color: "Black",
      gameFormat: "Tournaments"
    },
    {
      id: 7,
      date: "2024-02-25",
      opponent: "QueenQuest",
      result: "WIN",
      eloChange: "(+11 ELO Rating)",
      resultColor: "text-green-500",
      rating: "1900",
      opening: "Pirc Defense",
      moves: "41",
      timeControl: "5+0",
      source: "Online Games",
      gameType: "Blitz",
      color: "White",
      gameFormat: "Online Games"
    },
    {
      id: 8,
      date: "2024-02-20",
      opponent: "KingKrusher",
      result: "DRAW",
      eloChange: "(+0 ELO Rating)",
      resultColor: "text-gray-500",
      rating: "1925",
      opening: "English Opening",
      moves: "45",
      timeControl: "60+30",
      source: "PGN Upload",
      gameType: "Classical",
      color: "Black",
      gameFormat: "PGN Upload"
    },
    {
      id: 9,
      date: "2024-02-15",
      opponent: "CheckmateChamp",
      result: "LOSS",
      eloChange: "(-5 ELO Rating)",
      resultColor: "text-red-500",
      rating: "2150",
      opening: "Nimzo-Indian Defense",
      moves: "37",
      timeControl: "3+0",
      source: "Online Games",
      gameType: "Bullet",
      color: "White",
      gameFormat: "Online Games"
    },
    {
      id: 10,
      date: "2024-02-10",
      opponent: "TacticalTiger",
      result: "WIN",
      eloChange: "(+14 ELO Rating)",
      resultColor: "text-green-500",
      rating: "1850",
      opening: "Scandinavian Defense",
      moves: "48",
      timeControl: "15+15",
      source: "Tournaments",
      gameType: "Rapid",
      color: "Black",
      gameFormat: "Tournaments"
    },
    {
      id: 11,
      date: "2024-02-05",
      opponent: "EndgameExpert",
      result: "WIN",
      eloChange: "(+9 ELO Rating)",
      resultColor: "text-green-500",
      rating: "1795",
      opening: "Slav Defense",
      moves: "56",
      timeControl: "10+0",
      source: "PGN Upload",
      gameType: "Blitz",
      color: "White",
      gameFormat: "PGN Upload"
    }
  ];