on:
  pull_request:
    types: [opened]
jobs:
  create_trello_card:
    runs-on: ubuntu-latest
    steps:
      - name: Create Trello card
        run: |
          curl -X POST "https://api.trello.com/1/cards" \
          -d "name=${{ github.event.issue.title || github.event.pull_request.title }}" \
          -d "desc=${{ github.event.issue.html_url || github.event.pull_request.html_url }}" \
          -d "idList=6903349dd04d09902dacd14c" \
          -d "labels=GitHub" \
          -d "key=$TRELLO_KEY" \
          -d "token=$TRELLO_TOKEN"
        env:
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
